### ISSUE TITLE
Add validation that POST requests are in the correct format

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/orientation-project-python-23.SUM.A#13]
When making a POST request to add an Experience, Education or Skill, the API server should check it's in the correct format, including all the required fields. If it is not, it should return an error message and the appropriate HTTP status code.

This should also include writing a test inside of `test_pytest.py` as part of the feature to show that it works. If you're unfamiliar with Pytest, you should take a read inside the LMS for more instructions!

**Comment by Raajheer1** [comment]
Hey everyone! I am working on this issue and have PRed it above feel free to add any changes or comments to the PR!
