### ISSUE TITLE
Implement API route to return a specific Education

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/orientation-project-python-23.SUM.A#17]
On the `/resume/education` route, you should

- [ ] Return a specific Education when a GET request is made with an index as an input. The Education should be in a JSON format.

**Comment by kritgrover** [comment]
I think there's a typo in the issue name .it should be "Implement API route to return a specific Education" and not Skill.

**Comment by wrussell1999** [comment]
> I think there's a typo in the issue name .it should be "Implement API route to return a specific Education" and not Skill.

Good spot, updated!
