### ISSUE TITLE
Enable Cors on the Server Side

### ISSUE THREAD

**Issue by Ginohmk** [MLH-Fellowship/orientation-project-python-23.SUM.A#30]
## This Issue is regarding Cors not being enabled on the Server side.

- This issue prevents the client side from consuming the server endpoint. 
     - I suggest Cors is enabled on the server side

#### Error of CORS below.

![image](https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.A/assets/58771507/c4539d6c-a87a-43c3-9172-7e57bf435fc7)

**Comment by Ginohmk** [comment]
@wrussell1999
-  Please take a look at this, The Cors error prevents me from proceeding with the Issue I picked on the Frontend. I can fix this.

**Comment by wrussell1999** [comment]
> @wrussell1999
> 
> * Please take a look at this, The Cors error prevents me from proceeding with the Issue I picked on the Frontend. I can fix this.
>   or anyone can fix it with the instruction in the image below or this [link](https://stackoverflow.com/questions/28461001/python-flask-cors-issue) to Stackoverflow.
> 
> ##### Image
> ![image](https://user-images.githubusercontent.com/58771507/242992247-51b60d81-6cf8-49cb-a535-9c38755a08a8.png)

@Ginohmk you can install this module for the code base and commit it in to make it work

**Comment by Ginohmk** [comment]
Alright @wrussell1999 should I create a PR for this fix?

**Comment by wrussell1999** [comment]
@Ginohmk yes and reference this Issue
