### ISSUE TITLE
Edit existing Experience

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/orientation-project-python-23.SUM.A#8]
Using a `PUT` request for the `/resume/experience` route, update an existing Experience using its index position as an ID. As part of this, you should write a test in `test_pytest.py` to show it works.

**Comment by ahmedehabb** [comment]
I think this issue is blocked by issues of getting an existing experience by index since the code will be repeatable.
Once the pull request #24 is merged. 
I am planning to take the code done to retrieve an existing model by index and put it in a function then use it here also in these put issues.
